version: '2.1'
services:
  coupon-api:
    depends_on:
      - coupon-db
    image: coupon-api:1.0
    links:
      - coupon-db
    ports:
      - 5000:5000/tcp
    restart: always
  coupon-db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
    restart: always
